### ISSUE TITLE
setup-cpp step fails in Node 12

### ISSUE THREAD

**Issue by SK83RJOSH** [aminya/setup-cpp#123]
The latest version appears to have a syntax error somewhere, leading to a very noisy error log. I suspect this is caused by a change within a8d76c6b538f9bc09243b13387cc83478537cde1.

```
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:[27](https://github.com/SK83RJOSH/nifly-utils/actions/runs/3079336898/jobs/4975505857#step:5:28))
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by aminya** [comment]
I cannot reproduce this in the CI:
https://github.com/aminya/setup-cpp/actions/runs/3076474508

**Comment by aminya** [comment]
The issue seems to be Node 12 installed in the GitHub images. Not sure why the Parcel compilation is not generating proper code for Node 12

**Comment by aminya** [comment]
This is a bug in Parcel that is triggered when the optimizations are enabled. I am disabling the optimizations for now.

**Comment by aminya** [comment]
The actual reason was the terser config. I have enabled optimizations back!
